//ListContainer
export const PUSH_TO_CONTAINER = 'PUSH_TO_CONTAINER';
export const DELETE_FROM_CONTAINER = 'DELETE_FROM_CONTAINER';
export const SELECT_INDUSTRY = 'SELECT_INDUSTRY'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'