//ListContainer
export const PUSH_TO_CONTAINER = 'PUSH_TO_CONTAINER';
export const DELETE_FROM_CONTAINER = 'DELETE_FROM_CONTAINER';
export const SELECT_INDUSTRY = 'SELECT_INDUSTRY'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SELECT_COMPANY_SALARY = 'SELECT_COMPANY_SALARY'
export const SELECT_LEVEL_SALARY = 'SELECT_LEVEL_SALARY'