//ListforLevel
export const UPDATE_DATASOURCE = 'UPDATE_DATASOURCE';

//ListContainer
export const PUSH_TO_CONTAINER = 'PUSH_TO_CONTAINER';
export const DELETE_FROM_CONTAINER = 'DELETE_FROM_CONTAINER';